# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://ethanwhh.github.io' 
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Ethanwhh's Blog
# Description of the Site
description: Just do it! & Nothing is impossible!
# URL of Image of the Site
site-image: /assets/images/meta.png
# Keywords of the Site
site-keywords: Blog, 技术博客, Ethanwhh, 个人网站
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/3384815/pexels-photo-3384815.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: haihongwang2004@gmail.com
github_username: Ethanwhh
xiaohongshu_username: 632c820a000000002303ce09
bilibili_uid: 513196564

# Google Analytics
google-analytics: G-C34THPKYZN

# Name of the Author
author-name: Ethanwhh
# URL for the Image of the Author
author-image: /assets/images/author.png
# 60 Words About the Author
author-about: My name is Haihong Wang.🥰I am a senior student at Harbin Institute of Technology. And I am going to continue my further studies at the National University of Singapore. I am interested in various fields including Agent and LLM. Currently I'm focusing on Agent and Embodied AI. And I am a member of Datawhale, welcome to play and contribute to community development together. If you are interested in me, your contact is highly anticipated!
# URL to the Author's Profile
author-url: https://github.com/Ethanwhh

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
